CREATE TABLE public."TbOrderDummy"(
    --키
    "KeyCode" int8 GENERATED BY DEFAULT AS IDENTITY(INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    "MemberCode" int8 NOT NULL,
    "CenterCode" int8 NOT NULL,

    --오더 정보
    "UserCode" int8 NOT NULL DEFAULT 0,
    "UserName" varchar NOT NULL DEFAULT '',
    "DtRegist" TIMESTAMP NOT NULL DEFAULT now(),
    "DtUpdateLast" TIMESTAMP NOT NULL DEFAULT now(),
    "ReceiptTime" TIME NULL,
    "AllocTime" TIME NULL,
    "RunTime" TIME NULL,
    "FinishTime" TIME NULL,

    "OrderState" varchar NOT NULL DEFAULT '',
    "OrderStateOld" varchar NOT NULL DEFAULT '',
    "CancelReason" varchar NOT NULL DEFAULT '',
    "Share" BOOL NOT NULL DEFAULT false,
    "TaxBill" BOOL NOT NULL DEFAULT false,

    --의뢰자 정보
    "CallCompCode" int8 NOT NULL DEFAULT 0,
    "CallCompName" varchar NOT NULL DEFAULT '',
    "CallCustFrom" varchar NOT NULL DEFAULT '',
    "CallCustCodeE" int8 NOT NULL DEFAULT 0,
    "CallCustCodeK" int8 NOT NULL DEFAULT 0,
    "CallCustName" varchar NOT NULL DEFAULT '',
    "CallTelNo" varchar NOT NULL DEFAULT '',
    "CallTelNo2" varchar NOT NULL DEFAULT '',
    "CallDeptName" varchar NOT NULL DEFAULT '',
    "CallChargeName" varchar NOT NULL DEFAULT '',
    "CallDongBasic" varchar NOT NULL DEFAULT '',
    "CallAddress" varchar NOT NULL DEFAULT '',
    "CallDetailAddr" varchar NOT NULL DEFAULT '',
    "CallRemarks" varchar NOT NULL DEFAULT '',
    "CallMemo" varchar NOT NULL DEFAULT '',

    --출발지 정보
    "StartCustCodeE" int8 NOT NULL DEFAULT 0,
    "StartCustCodeK" int8 NOT NULL DEFAULT 0,
    "StartCustName" varchar NOT NULL DEFAULT '',
    "StartTelNo" varchar NOT NULL DEFAULT '',
    "StartTelNo2" varchar NOT NULL DEFAULT '',
    "StartDeptName" varchar NOT NULL DEFAULT '',
    "StartChargeName" varchar NOT NULL DEFAULT '',
    "StartDongBasic" varchar NOT NULL DEFAULT '',
    "StartAddress" varchar NOT NULL DEFAULT '',
    "StartDetailAddr" varchar NOT NULL DEFAULT '',
    "StartSiDo" varchar NOT NULL DEFAULT '',
    "StartGunGu" varchar NOT NULL DEFAULT '',
    "StartDongRi" varchar NOT NULL DEFAULT '',
    "StartLon" int4 NOT NULL DEFAULT 0,
    "StartLat" int4 NOT NULL DEFAULT 0,
    "StartSignImgUrl" varchar NULL,
    "StartDtSign" TIMESTAMP NULL,

    --도착지 정보
    "DestCustCodeE" int8 NOT NULL DEFAULT 0,
    "DestCustCodeK" int8 NOT NULL DEFAULT 0,
    "DestCustName" varchar NOT NULL DEFAULT '',
    "DestTelNo" varchar NOT NULL DEFAULT '',
    "DestTelNo2" varchar NOT NULL DEFAULT '',
    "DestDeptName" varchar NOT NULL DEFAULT '',
    "DestChargeName" varchar NOT NULL DEFAULT '',
    "DestDongBasic" varchar NOT NULL DEFAULT '',
    "DestAddress" varchar NOT NULL DEFAULT '',
    "DestDetailAddr" varchar NOT NULL DEFAULT '',
    "DestSiDo" varchar NOT NULL DEFAULT '',
    "DestGunGu" varchar NOT NULL DEFAULT '',
    "DestDongRi" varchar NOT NULL DEFAULT '',
    "DestLon" int4 DEFAULT 0 NOT NULL,
    "DestLat" int4 DEFAULT 0 NOT NULL,
    "DestSignImgUrl" varchar NULL,
    "DestDtSign" TIMESTAMP NULL,

    --예약 및 요금(이름 유지)
    "Reserve" BOOL NOT NULL DEFAULT false,
    "DtReserve" TIMESTAMP NULL,
    "ReserveBreakMinute" int4 DEFAULT 0 NOT NULL,

    "FeeBasic" int4 DEFAULT 0 NOT NULL,
    "FeeTotal" int4 DEFAULT 0 NOT NULL,
    "FeeCommi" int4 DEFAULT 0 NOT NULL,
    "FeeDriver" int4 DEFAULT 0 NOT NULL,
    "FeePlus" int4 DEFAULT 0 NOT NULL,
    "FeeMinus" int4 DEFAULT 0 NOT NULL,
    "FeeConn" int4 DEFAULT 0 NOT NULL,
    "FeeType" varchar NOT NULL DEFAULT '',

    --배송타입, 차량타입, 출, 도착 일시
    "MovilityFlag" varchar NOT NULL DEFAULT '',
    "DeliverFlag" varchar NOT NULL DEFAULT '',
    "StartDateFlag" varchar NOT NULL DEFAULT '',
    "StartDateDetail" varchar NOT NULL DEFAULT '',
    "DestDateFlag" varchar NOT NULL DEFAULT '',
    "DestDateDetail" varchar NOT NULL DEFAULT '',

    --화물 옵션
    "CarWeightFlag" varchar NOT NULL DEFAULT '',
    "TruckDetailFlag" varchar NOT NULL DEFAULT '',
    "StartLoadFlag" varchar NOT NULL DEFAULT '',
    "DestUnloadFlag" varchar NOT NULL DEFAULT '',

    --화물, 퀵 공용정보
    "DeliverMemo" varchar NOT NULL DEFAULT '',

    --기사 정보
    "DriverCode" int8 DEFAULT 0 NOT NULL,
    "DriverId" varchar NOT NULL DEFAULT '',
    "DriverName" varchar NOT NULL DEFAULT '',
    "DriverTelNo" varchar NOT NULL DEFAULT '',
    "DriverMemberCode" int8 DEFAULT 0 NOT NULL,
    "DriverCenterId" varchar NOT NULL DEFAULT '',
    "DriverCenterName" varchar NOT NULL DEFAULT '',
    "DriverBusinessNo" varchar NOT NULL DEFAULT '',

    --외부 앱 정보(이름 유지)
    "Insung1SeqNo" varchar NOT NULL DEFAULT '',
    "Insung1State" varchar NOT NULL DEFAULT '',
    "Insung2SeqNo" varchar NOT NULL DEFAULT '',
    "Insung2State" varchar NOT NULL DEFAULT '',
    "Cargo24SeqNo" varchar NOT NULL DEFAULT '',
    "Cargo24State" varchar NOT NULL DEFAULT '',
    "OnecallSeqNo" varchar NOT NULL DEFAULT '',
    "OnecallState" varchar NOT NULL DEFAULT '',

    CONSTRAINT "TbOrder_Dummy_pkey" PRIMARY KEY("KeyCode")
);

CREATE TABLE public."TbOrder"(
    --키
    "KeyCode" int8 GENERATED BY DEFAULT AS IDENTITY(INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    "MemberCode" int8 NOT NULL,
    "CenterCode" int8 NOT NULL,

    --오더 정보
    "UserCode" int8 NOT NULL DEFAULT 0,
    "UserName" varchar NOT NULL DEFAULT '',
    "DtRegist" TIMESTAMP NOT NULL DEFAULT now(),
    "DtUpdateLast" TIMESTAMP NOT NULL DEFAULT now(),
    "ReceiptTime" TIME NULL,
    "AllocTime" TIME NULL,
    "RunTime" TIME NULL,
    "FinishTime" TIME NULL,

    "OrderState" varchar NOT NULL DEFAULT '',
    "OrderStateOld" varchar NOT NULL DEFAULT '',
    "CancelReason" varchar NOT NULL DEFAULT '',
    "Share" BOOL NOT NULL DEFAULT false,
    "TaxBill" BOOL NOT NULL DEFAULT false,

    --의뢰자 정보
    "CallCompCode" int8 NOT NULL DEFAULT 0,
    "CallCompName" varchar NOT NULL DEFAULT '',
    "CallCustFrom" varchar NOT NULL DEFAULT '',
    "CallCustCodeE" int8 NOT NULL DEFAULT 0,
    "CallCustCodeK" int8 NOT NULL DEFAULT 0,
    "CallCustName" varchar NOT NULL DEFAULT '',
    "CallTelNo" varchar NOT NULL DEFAULT '',
    "CallTelNo2" varchar NOT NULL DEFAULT '',
    "CallDeptName" varchar NOT NULL DEFAULT '',
    "CallChargeName" varchar NOT NULL DEFAULT '',
    "CallDongBasic" varchar NOT NULL DEFAULT '',
    "CallAddress" varchar NOT NULL DEFAULT '',
    "CallDetailAddr" varchar NOT NULL DEFAULT '',
    "CallRemarks" varchar NOT NULL DEFAULT '',
    "CallMemo" varchar NOT NULL DEFAULT '',

    --출발지 정보
    "StartCustCodeE" int8 NOT NULL DEFAULT 0,
    "StartCustCodeK" int8 NOT NULL DEFAULT 0,
    "StartCustName" varchar NOT NULL DEFAULT '',
    "StartTelNo" varchar NOT NULL DEFAULT '',
    "StartTelNo2" varchar NOT NULL DEFAULT '',
    "StartDeptName" varchar NOT NULL DEFAULT '',
    "StartChargeName" varchar NOT NULL DEFAULT '',
    "StartDongBasic" varchar NOT NULL DEFAULT '',
    "StartAddress" varchar NOT NULL DEFAULT '',
    "StartDetailAddr" varchar NOT NULL DEFAULT '',
    "StartSiDo" varchar NOT NULL DEFAULT '',
    "StartGunGu" varchar NOT NULL DEFAULT '',
    "StartDongRi" varchar NOT NULL DEFAULT '',
    "StartLon" int4 NOT NULL DEFAULT 0,
    "StartLat" int4 NOT NULL DEFAULT 0,
    "StartSignImgUrl" varchar NULL,
    "StartDtSign" TIMESTAMP NULL,

    --도착지 정보
    "DestCustCodeE" int8 NOT NULL DEFAULT 0,
    "DestCustCodeK" int8 NOT NULL DEFAULT 0,
    "DestCustName" varchar NOT NULL DEFAULT '',
    "DestTelNo" varchar NOT NULL DEFAULT '',
    "DestTelNo2" varchar NOT NULL DEFAULT '',
    "DestDeptName" varchar NOT NULL DEFAULT '',
    "DestChargeName" varchar NOT NULL DEFAULT '',
    "DestDongBasic" varchar NOT NULL DEFAULT '',
    "DestAddress" varchar NOT NULL DEFAULT '',
    "DestDetailAddr" varchar NOT NULL DEFAULT '',
    "DestSiDo" varchar NOT NULL DEFAULT '',
    "DestGunGu" varchar NOT NULL DEFAULT '',
    "DestDongRi" varchar NOT NULL DEFAULT '',
    "DestLon" int4 DEFAULT 0 NOT NULL,
    "DestLat" int4 DEFAULT 0 NOT NULL,
    "DestSignImgUrl" varchar NULL,
    "DestDtSign" TIMESTAMP NULL,

    --예약 및 요금(이름 유지)
    "Reserve" BOOL NOT NULL DEFAULT false,
    "DtReserve" TIMESTAMP NULL,
    "ReserveBreakMinute" int4 DEFAULT 0 NOT NULL,

    "FeeBasic" int4 DEFAULT 0 NOT NULL,
    "FeeTotal" int4 DEFAULT 0 NOT NULL,
    "FeeCommi" int4 DEFAULT 0 NOT NULL,
    "FeeDriver" int4 DEFAULT 0 NOT NULL,
    "FeePlus" int4 DEFAULT 0 NOT NULL,
    "FeeMinus" int4 DEFAULT 0 NOT NULL,
    "FeeConn" int4 DEFAULT 0 NOT NULL,
    "FeeType" varchar NOT NULL DEFAULT '',

    --배송타입, 차량타입, 출, 도착 일시
    "MovilityFlag" varchar NOT NULL DEFAULT '',
    "DeliverFlag" varchar NOT NULL DEFAULT '',
    "StartDateFlag" varchar NOT NULL DEFAULT '',
    "StartDateDetail" varchar NOT NULL DEFAULT '',
    "DestDateFlag" varchar NOT NULL DEFAULT '',
    "DestDateDetail" varchar NOT NULL DEFAULT '',

    --화물 옵션
    "CarWeightFlag" varchar NOT NULL DEFAULT '',
    "TruckDetailFlag" varchar NOT NULL DEFAULT '',
    "StartLoadFlag" varchar NOT NULL DEFAULT '',
    "DestUnloadFlag" varchar NOT NULL DEFAULT '',

    --화물, 퀵 공용정보
    "DeliverMemo" varchar NOT NULL DEFAULT '',

    --기사 정보
    "DriverCode" int8 DEFAULT 0 NOT NULL,
    "DriverId" varchar NOT NULL DEFAULT '',
    "DriverName" varchar NOT NULL DEFAULT '',
    "DriverTelNo" varchar NOT NULL DEFAULT '',
    "DriverMemberCode" int8 DEFAULT 0 NOT NULL,
    "DriverCenterId" varchar NOT NULL DEFAULT '',
    "DriverCenterName" varchar NOT NULL DEFAULT '',
    "DriverBusinessNo" varchar NOT NULL DEFAULT '',

    --외부 앱 정보(이름 유지)
    "Insung1SeqNo" varchar NOT NULL DEFAULT '',
    "Insung1State" varchar NOT NULL DEFAULT '',
    "Insung2SeqNo" varchar NOT NULL DEFAULT '',
    "Insung2State" varchar NOT NULL DEFAULT '',
    "Cargo24SeqNo" varchar NOT NULL DEFAULT '',
    "Cargo24State" varchar NOT NULL DEFAULT '',
    "OnecallSeqNo" varchar NOT NULL DEFAULT '',
    "OnecallState" varchar NOT NULL DEFAULT '',


    --PK는 KeyCode와 파티션 키인 DtRegist의 조합이어야 합니다.
    CONSTRAINT "TbOrder_pkey" PRIMARY KEY("KeyCode", "DtRegist")
) PARTITION BY RANGE ("DtRegist");

CREATE TABLE public."TbOrder_Default"
    PARTITION OF public."TbOrder"
    DEFAULT;

CREATE TABLE public."TbOrder_2026_01_05"
  PARTITION OF public."TbOrder"
  FOR VALUES FROM ('2026-01-05 00:00:00') TO ('2026-01-06 00:00:00');